<?php

use Illuminate\Database\Seeder;

class nationalities extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('nationalities')->delete();
        DB::table('nationalities')->insert(array(


        // Call The Defined Factory From UserFactory
        // factory(App\Country::class, 13)->create();

            array('country_code' => 'US', 'name_en' => 'United States', 'name_ar' => 'الولايات المتحدة', 'slug' => 'الولايات-المتحدة'),
            array('country_code' => 'CA', 'name_en' => 'Canada', 'name_ar' => 'كندا', 'slug' => 'كندا'),
            array('country_code' => 'AF', 'name_en' => 'Afghanistan', 'name_ar' => 'أفغانستان', 'slug' => 'أفغانستان'),
            array('country_code' => 'AL', 'name_en' => 'Albania', 'name_ar' => 'ألبانيا', 'slug' => 'ألبانيا'),
            array('country_code' => 'DZ', 'name_en' => 'Algeria', 'name_ar' => 'الجزائر', 'slug' => 'الجزائر'),
            array('country_code' => 'AS', 'name_en' => 'American Samoa', 'name_ar' => 'ساموا الأمريكية', 'slug' => 'ساموا-الأمريكية'),
            array('country_code' => 'AD', 'name_en' => 'Andorra', 'name_ar' => 'أندورا', 'slug' => 'أندورا'),
            array('country_code' => 'AO', 'name_en' => 'Angola', 'name_ar' => 'أنغولا', 'slug' => 'أنغولا'),
            array('country_code' => 'AI', 'name_en' => 'Anguilla', 'name_ar' => 'أنغويلا', 'slug' => 'أنغويلا'),
            array('country_code' => 'AQ', 'name_en' => 'Antarctica', 'name_ar' => 'أنتاركتيكا', 'slug' => 'أنتاركتيكا'),
            array('country_code' => 'AG', 'name_en' => 'Antigua and/or Barbuda', 'name_ar' => 'أنتيغوا وبربودا', 'slug' => 'أنتيغوا-وبربودا'),
            array('country_code' => 'AR', 'name_en' => 'Argentina', 'name_ar' => 'الأرجنتين', 'slug' => 'الأرجنتين'),
            array('country_code' => 'AM', 'name_en' => 'Armenia', 'name_ar' => 'أرمينيا', 'slug' => 'أرمينيا'),
            array('country_code' => 'AW', 'name_en' => 'Aruba', 'name_ar' => 'أروبا', 'slug' => 'أروبا'),
            array('country_code' => 'AU', 'name_en' => 'Australia', 'name_ar' => 'أستراليا', 'slug' => 'أستراليا'),
            array('country_code' => 'AT', 'name_en' => 'Austria', 'name_ar' => 'النمسا', 'slug' => 'النمسا'),
            array('country_code' => 'AZ', 'name_en' => 'Azerbaijan', 'name_ar' => 'أذربيجان', 'slug' => 'أذربيجان'),
            array('country_code' => 'BS', 'name_en' => 'Bahamas', 'name_ar' => 'البهاما', 'slug' => 'البهاما'),
            array('country_code' => 'BH', 'name_en' => 'Bahrain', 'name_ar' => 'البحرين', 'slug' => 'البحرين'),
            array('country_code' => 'BD', 'name_en' => 'Bangladesh', 'name_ar' => 'بنغلاديش', 'slug' => 'بنغلاديش'),
            array('country_code' => 'BB', 'name_en' => 'Barbados', 'name_ar' => 'بربادوس', 'slug' => 'بربادوس'),
            array('country_code' => 'BY', 'name_en' => 'Belarus', 'name_ar' => 'بيلاروس', 'slug' => 'بيلاروس'),
            array('country_code' => 'BE', 'name_en' => 'Belgium', 'name_ar' => 'بلجيكا', 'slug' => 'بلجيكا'),
            array('country_code' => 'BZ', 'name_en' => 'Belize', 'name_ar' => 'بليز', 'slug' => 'بليز'),
            array('country_code' => 'BJ', 'name_en' => 'Benin', 'name_ar' => 'بنين', 'slug' => 'بنين'),
            array('country_code' => 'BM', 'name_en' => 'Bermuda', 'name_ar' => 'برمودا', 'slug' => 'برمودا'),
            array('country_code' => 'BT', 'name_en' => 'Bhutan', 'name_ar' => 'بوتان', 'slug' => 'بوتان'),
            array('country_code' => 'BO', 'name_en' => 'Bolivia', 'name_ar' => 'بوليفيا', 'slug' => 'بوليفيا'),
            array('country_code' => 'BA', 'name_en' => 'Bosnia and Herzegovina', 'name_ar' => 'البوسنة والهرسك', 'slug' => 'البوسنة-والهرسك'),
            array('country_code' => 'BW', 'name_en' => 'Botswana', 'name_ar' => 'بتسوانا', 'slug' => 'بتسوانا'),
            array('country_code' => 'BV', 'name_en' => 'Bouvet Island', 'name_ar' => 'جزيرة بوفيت', 'slug' => 'جزيرة-بوفيت'),
            array('country_code' => 'BR', 'name_en' => 'Brazil', 'name_ar' => 'البرازيل', 'slug' => 'البرازيل'),
            array('country_code' => 'IO', 'name_en' => 'British lndian Ocean Territory', 'name_ar' => 'الإقليم البريطاني في المحيط الهندي', 'slug' => 'الإقليم-البريطاني-في-المحيط-الهندي'),
            array('country_code' => 'BN', 'name_en' => 'Brunei Darussalam', 'name_ar' => 'بروناي', 'slug' => 'بروناي'),
            array('country_code' => 'BG', 'name_en' => 'Bulgaria', 'name_ar' => 'بلغاريا', 'slug' => 'بلغاريا'),
            array('country_code' => 'BF', 'name_en' => 'Burkina Faso', 'name_ar' => 'بوركينا فاسو', 'slug' => 'بوركينا-فاسو'),
            array('country_code' => 'BI', 'name_en' => 'Burundi', 'name_ar' => 'بوروندي', 'slug' => 'بوروندي'),
            array('country_code' => 'KH', 'name_en' => 'Cambodia', 'name_ar' => 'كمبوديا', 'slug' => 'كمبوديا'),
            array('country_code' => 'CM', 'name_en' => 'Cameroon', 'name_ar' => 'الكاميرون', 'slug' => 'الكاميرون'),
            array('country_code' => 'CV', 'name_en' => 'Cape Verde', 'name_ar' => 'الرأس الأخضر', 'slug' => 'الرأس-الأخضر'),
            array('country_code' => 'KY', 'name_en' => 'Cayman Islands', 'name_ar' => 'جزر كايمان', 'slug' => 'جزر-كايمان'),
            array('country_code' => 'CF', 'name_en' => 'Central African Republic', 'name_ar' => 'جمهورية أفريقيا الوسطى', 'slug' => 'جمهورية-أفريقيا-الوسطى'),
            array('country_code' => 'TD', 'name_en' => 'Chad', 'name_ar' => 'تشاد', 'slug' => 'تشاد'),
            array('country_code' => 'CL', 'name_en' => 'Chile', 'name_ar' => 'تشيلي', 'slug' => 'تشيلي'),
            array('country_code' => 'CN', 'name_en' => 'China', 'name_ar' => 'الصين', 'slug' => 'الصين'),
            array('country_code' => 'CX', 'name_en' => 'Christmas Island', 'name_ar' => 'جزيرة الكريسماس', 'slug' => 'جزيرة-الكريسماس'),
            array('country_code' => 'CC', 'name_en' => 'Cocos (Keeling) Islands', 'name_ar' => 'جزر كوكوس (كيلينغ)', 'slug' => 'جزر-كوكوس-كيلينغ'),
            array('country_code' => 'CO', 'name_en' => 'Colombia', 'name_ar' => 'كولومبيا', 'slug' => 'كولومبيا'),
            array('country_code' => 'KM', 'name_en' => 'Comoros', 'name_ar' => 'جزر القمر', 'slug' => 'جزر-القمر'),
            array('country_code' => 'CG', 'name_en' => 'Congo', 'name_ar' => 'الكونغو - برازافيل', 'slug' => 'الكونغو-برازافيل'),
            array('country_code' => 'CK', 'name_en' => 'Cook Islands', 'name_ar' => 'جزر كوك', 'slug' => 'جزر-كوك'),
            array('country_code' => 'CR', 'name_en' => 'Costa Rica', 'name_ar' => 'كوستاريكا', 'slug' => 'كوستاريكا'),
            array('country_code' => 'HR', 'name_en' => 'Croatia (Hrvatska)', 'name_ar' => 'كرواتيا', 'slug' => 'كرواتيا'),
            array('country_code' => 'CU', 'name_en' => 'Cuba', 'name_ar' => 'كوبا', 'slug' => 'كوبا'),
            array('country_code' => 'CY', 'name_en' => 'Cyprus', 'name_ar' => 'قبرص', 'slug' => 'قبرص'),
            array('country_code' => 'CZ', 'name_en' => 'Czech Republic', 'name_ar' => 'التشيك', 'slug' => 'التشيك'),
            array('country_code' => 'CD', 'name_en' => 'Democratic Republic of Congo', 'name_ar' => 'الكونغو - كينشاسا', 'slug' => 'الكونغو-كينشاسا'),
            array('country_code' => 'DK', 'name_en' => 'Denmark', 'name_ar' => 'الدانمرك', 'slug' => 'الدانمرك'),
            array('country_code' => 'DJ', 'name_en' => 'Djibouti', 'name_ar' => 'جيبوتي', 'slug' => 'جيبوتي'),
            array('country_code' => 'DM', 'name_en' => 'Dominica', 'name_ar' => 'دومينيكا', 'slug' => 'دومينيكا'),
            array('country_code' => 'DO', 'name_en' => 'Dominican Republic', 'name_ar' => 'جمهورية الدومينيكان', 'slug' => 'جمهورية-الدومينيكان'),
            array('country_code' => 'TP', 'name_en' => 'East Timor', 'name_ar' => 'تيمور الشرقية', 'slug' => 'تيمور-الشرقية'),
            array('country_code' => 'EC', 'name_en' => 'Ecudaor', 'name_ar' => 'الإكوادور', 'slug' => 'الإكوادور'),
            array('country_code' => 'EG', 'name_en' => 'Egypt', 'name_ar' => 'مصر', 'slug' => 'مصر'),
            array('country_code' => 'SV', 'name_en' => 'El Salvador', 'name_ar' => 'السلفادور', 'slug' => 'السلفادور'),
            array('country_code' => 'GQ', 'name_en' => 'Equatorial Guinea', 'name_ar' => 'غينيا الاستوائية', 'slug' => 'غينيا-الاستوائية'),
            array('country_code' => 'ER', 'name_en' => 'Eritrea', 'name_ar' => 'إريتريا', 'slug' => 'إريتريا'),
            array('country_code' => 'EE', 'name_en' => 'Estonia', 'name_ar' => 'إستونيا', 'slug' => 'إستونيا'),
            array('country_code' => 'ET', 'name_en' => 'Ethiopia', 'name_ar' => 'إثيوبيا', 'slug' => 'إثيوبيا'),
            array('country_code' => 'FK', 'name_en' => 'Falkland Islands (Malvinas)', 'name_ar' => 'جزر فوكلاند', 'slug' => 'جزر-فوكلاند'),
            array('country_code' => 'FO', 'name_en' => 'Faroe Islands', 'name_ar' => 'جزر فارو', 'slug' => 'جزر-فارو'),
            array('country_code' => 'FJ', 'name_en' => 'Fiji', 'name_ar' => 'فيجي', 'slug' => 'فيجي'),
            array('country_code' => 'FI', 'name_en' => 'Finland', 'name_ar' => 'فنلندا', 'slug' => 'فنلندا'),
            array('country_code' => 'FR', 'name_en' => 'France', 'name_ar' => 'فرنسا', 'slug' => 'فرنسا'),
            array('country_code' => 'FX', 'name_en' => 'France, Metropolitan', 'name_ar' => 'فرنسا ، متروبوليتان', 'slug' => 'فرنسا-متروبوليتان'),
            array('country_code' => 'GF', 'name_en' => 'French Guiana', 'name_ar' => 'غويانا الفرنسية', 'slug' => 'غويانا-الفرنسية'),
            array('country_code' => 'PF', 'name_en' => 'French Polynesia', 'name_ar' => 'بولينيزيا الفرنسية', 'slug' => 'بولينيزيا-الفرنسية'),
            array('country_code' => 'TF', 'name_en' => 'French Southern Territories', 'name_ar' => 'الأقاليم الجنوبية الفرنسية', 'slug' => 'الأقاليم-الجنوبية-الفرنسية'),
            array('country_code' => 'GA', 'name_en' => 'Gabon', 'name_ar' => 'الغابون', 'slug' => 'الغابون'),
            array('country_code' => 'GM', 'name_en' => 'Gambia', 'name_ar' => 'غامبيا', 'slug' => 'غامبيا'),
            array('country_code' => 'GE', 'name_en' => 'Georgia', 'name_ar' => 'جورجيا', 'slug' => 'جورجيا'),
            array('country_code' => 'DE', 'name_en' => 'Germany', 'name_ar' => 'ألمانيا', 'slug' => 'ألمانيا'),
            array('country_code' => 'GH', 'name_en' => 'Ghana', 'name_ar' => 'غانا', 'slug' => 'غانا'),
            array('country_code' => 'GI', 'name_en' => 'Gibraltar', 'name_ar' => 'جبل طارق', 'slug' => 'جبل طارق'),
            array('country_code' => 'GR', 'name_en' => 'Greece', 'name_ar' => 'اليونان', 'slug' => 'اليونان'),
            array('country_code' => 'GL', 'name_en' => 'Greenland', 'name_ar' => 'غرينلاند', 'slug' => 'غرينلاند'),
            array('country_code' => 'GD', 'name_en' => 'Grenada', 'name_ar' => 'غرينادا', 'slug' => 'غرينادا'),
            array('country_code' => 'GP', 'name_en' => 'Guadeloupe', 'name_ar' => 'غوادلوب', 'slug' => 'غوادلوب'),
            array('country_code' => 'GU', 'name_en' => 'Guam', 'name_ar' => 'غوام', 'slug' => 'غوام'),
            array('country_code' => 'GT', 'name_en' => 'Guatemala', 'name_ar' => 'غواتيمالا', 'slug' => 'غواتيمالا'),
            array('country_code' => 'GN', 'name_en' => 'Guinea', 'name_ar' => 'غينيا', 'slug' => 'غينيا'),
            array('country_code' => 'GW', 'name_en' => 'Guinea-Bissau', 'name_ar' => 'غينيا بيساو', 'slug' => 'غينيا-بيساو'),
            array('country_code' => 'GY', 'name_en' => 'Guyana', 'name_ar' => 'غيانا', 'slug' => 'غيانا'),
            array('country_code' => 'HT', 'name_en' => 'Haiti', 'name_ar' => 'هايتي', 'slug' => 'هايتي'),
            array('country_code' => 'HM', 'name_en' => 'Heard and Mc Donald Islands', 'name_ar' => 'هيرد وجزر ماكدونالد', 'slug' => 'هيرد-وجزر-ماكدونالد'),
            array('country_code' => 'HN', 'name_en' => 'Honduras', 'name_ar' => 'هندوراس', 'slug' => 'هندوراس'),
            array('country_code' => 'HK', 'name_en' => 'Hong Kong', 'name_ar' => 'هونغ كونغ الصينية', 'slug' => 'هونغ-كونغ-الصينية'),
            array('country_code' => 'HU', 'name_en' => 'Hungary', 'name_ar' => 'هنغاريا', 'slug' => 'هنغاريا'),
            array('country_code' => 'IS', 'name_en' => 'Iceland', 'name_ar' => 'أيسلندا', 'slug' => 'أيسلندا'),
            array('country_code' => 'IN', 'name_en' => 'India', 'name_ar' => 'الهند', 'slug' => 'الهند'),
            array('country_code' => 'ID', 'name_en' => 'Indonesia', 'name_ar' => 'إندونيسيا', 'slug' => 'إندونيسيا'),
            array('country_code' => 'IR', 'name_en' => 'Iran (Islamic Republic of)', 'name_ar' => 'إيران', 'slug' => 'إيران'),
            array('country_code' => 'IQ', 'name_en' => 'Iraq', 'name_ar' => 'العراق', 'slug' => 'العراق'),
            array('country_code' => 'IE', 'name_en' => 'Ireland', 'name_ar' => 'أيرلندا', 'slug' => 'أيرلندا'),
            array('country_code' => 'IL', 'name_en' => 'Israel', 'name_ar' => 'إسرائيل', 'slug' => 'إسرائيل'),
            array('country_code' => 'IT', 'name_en' => 'Italy', 'name_ar' => 'إيطاليا', 'slug' => 'إيطاليا'),
            array('country_code' => 'CI', 'name_en' => 'Ivory Coast', 'name_ar' => 'ساحل العاج', 'slug' => 'ساحل-العاج'),
            array('country_code' => 'JM', 'name_en' => 'Jamaica', 'name_ar' => 'جامايكا', 'slug' => 'جامايكا'),
            array('country_code' => 'JP', 'name_en' => 'Japan', 'name_ar' => 'اليابان', 'slug' => 'اليابان'),
            array('country_code' => 'JO', 'name_en' => 'Jordan', 'name_ar' => 'الأردن', 'slug' => 'الأردن'),
            array('country_code' => 'KZ', 'name_en' => 'Kazakhstan', 'name_ar' => 'كازاخستان', 'slug' => 'كازاخستان'),
            array('country_code' => 'KE', 'name_en' => 'Kenya', 'name_ar' => 'كينيا', 'slug' => 'كينيا'),
            array('country_code' => 'KI', 'name_en' => 'Kiribati', 'name_ar' => 'كيريباتي', 'slug' => 'كيريباتي'),
            array('country_code' => 'KP', 'name_en' => 'Korea, Democratic People\'s Republic of', 'name_ar' => 'كوريا الشمالية', 'slug' => 'كوريا-الشمالية'),
            array('country_code' => 'KR', 'name_en' => 'Korea, Republic of', 'name_ar' => 'كوريا الجنوبية', 'slug' => 'كوريا-الجنوبية'),
            array('country_code' => 'KW', 'name_en' => 'Kuwait', 'name_ar' => 'الكويت', 'slug' => 'الكويت'),
            array('country_code' => 'KG', 'name_en' => 'Kyrgyzstan', 'name_ar' => 'قيرغيزستان', 'slug' => 'قيرغيزستان'),
            array('country_code' => 'LA', 'name_en' => 'Lao People\'s Democratic Republic', 'name_ar' => 'لاوس', 'slug' => 'لاوس'),
            array('country_code' => 'LV', 'name_en' => 'Latvia', 'name_ar' => 'لاتفيا', 'slug' => 'لاتفيا'),
            array('country_code' => 'LB', 'name_en' => 'Lebanon', 'name_ar' => 'لبنان', 'slug' => 'لبنان'),
            array('country_code' => 'LS', 'name_en' => 'Lesotho', 'name_ar' => 'ليسوتو', 'slug' => 'ليسوتو'),
            array('country_code' => 'LR', 'name_en' => 'Liberia', 'name_ar' => 'ليبيريا', 'slug' => 'ليبيريا'),
            array('country_code' => 'LY', 'name_en' => 'Libyan Arab Jamahiriya', 'name_ar' => 'ليبيا', 'slug' => 'ليبيا'),
            array('country_code' => 'LI', 'name_en' => 'Liechtenstein', 'name_ar' => 'ليختنشتاين', 'slug' => 'ليختنشتاين'),
            array('country_code' => 'LT', 'name_en' => 'Lithuania', 'name_ar' => 'ليتوانيا', 'slug' => 'ليتوانيا'),
            array('country_code' => 'LU', 'name_en' => 'Luxembourg', 'name_ar' => 'لوكسمبورغ', 'slug' => 'لوكسمبورغ'),
            array('country_code' => 'MO', 'name_en' => 'Macau', 'name_ar' => 'مكاو الصينية (منطقة إدارية خاصة)', 'slug' => 'مكاو-الصينية'),
            array('country_code' => 'MK', 'name_en' => 'Macedonia', 'name_ar' => 'مقدونيا', 'slug' => 'مقدونيا'),
            array('country_code' => 'MG', 'name_en' => 'Madagascar', 'name_ar' => 'مدغشقر', 'slug' => 'مدغشقر'),
            array('country_code' => 'MW', 'name_en' => 'Malawi', 'name_ar' => 'ملاوي', 'slug' => 'ملاوي'),
            array('country_code' => 'MY', 'name_en' => 'Malaysia', 'name_ar' => 'ماليزيا', 'slug' => 'ماليزيا'),
            array('country_code' => 'MV', 'name_en' => 'Maldives', 'name_ar' => 'جزر المالديف', 'slug' => 'جزر-المالديف'),
            array('country_code' => 'ML', 'name_en' => 'Mali', 'name_ar' => 'مالي', 'slug' => 'مالي'),
            array('country_code' => 'MT', 'name_en' => 'Malta', 'name_ar' => 'مالطا', 'slug' => 'مالطا'),
            array('country_code' => 'MH', 'name_en' => 'Marshall Islands', 'name_ar' => 'جزر مارشال', 'slug' => 'جزر-مارشال'),
            array('country_code' => 'MQ', 'name_en' => 'Martinique', 'name_ar' => 'جزر المارتينيك', 'slug' => 'جزر-المارتينيك'),
            array('country_code' => 'MR', 'name_en' => 'Mauritania', 'name_ar' => 'موريتانيا', 'slug' => 'موريتانيا'),
            array('country_code' => 'MU', 'name_en' => 'Mauritius', 'name_ar' => 'موريشيوس', 'slug' => 'موريشيوس'),
            array('country_code' => 'TY', 'name_en' => 'Mayotte', 'name_ar' => 'مايوت', 'slug' => 'مايوت'),
            array('country_code' => 'MX', 'name_en' => 'Mexico', 'name_ar' => 'المكسيك', 'slug' => 'المكسيك'),
            array('country_code' => 'FM', 'name_en' => 'Micronesia, Federated States of', 'name_ar' => 'ميكرونيزيا', 'slug' => 'ميكرونيزيا'),
            array('country_code' => 'MD', 'name_en' => 'Moldova, Republic of', 'name_ar' => 'مولدوفا', 'slug' => 'مولدوفا'),
            array('country_code' => 'MC', 'name_en' => 'Monaco', 'name_ar' => 'موناكو', 'slug' => 'موناكو'),
            array('country_code' => 'MN', 'name_en' => 'Mongolia', 'name_ar' => 'منغوليا', 'slug' => 'منغوليا'),
            array('country_code' => 'MS', 'name_en' => 'Montserrat', 'name_ar' => 'مونتسرات', 'slug' => 'مونتسرات'),
            array('country_code' => 'MA', 'name_en' => 'Morocco', 'name_ar' => 'المغرب', 'slug' => 'المغرب'),
            array('country_code' => 'MZ', 'name_en' => 'Mozambique', 'name_ar' => 'موزمبيق', 'slug' => 'موزمبيق'),
            array('country_code' => 'MM', 'name_en' => 'Myanmar', 'name_ar' => 'ميانمار (بورما)', 'slug' => 'ميانمار-بورما'),
            array('country_code' => 'NA', 'name_en' => 'Namibia', 'name_ar' => 'ناميبيا', 'slug' => 'ناميبيا'),
            array('country_code' => 'NR', 'name_en' => 'Nauru', 'name_ar' => 'ناورو', 'slug' => 'ناورو'),
            array('country_code' => 'NP', 'name_en' => 'Nepal', 'name_ar' => 'نيبال', 'slug' => 'نيبال'),
            array('country_code' => 'NL', 'name_en' => 'Netherlands', 'name_ar' => 'هولندا', 'slug' => 'هولندا'),
            array('country_code' => 'AN', 'name_en' => 'Netherlands Antilles', 'name_ar' => 'جزر الأنتيل الهولندية', 'slug' => 'جزر-الأنتيل-الهولندية'),
            array('country_code' => 'NC', 'name_en' => 'New Caledonia', 'name_ar' => 'كاليدونيا الجديدة', 'slug' => 'كاليدونيا-الجديدة'),
            array('country_code' => 'NZ', 'name_en' => 'New Zealand', 'name_ar' => 'نيوزيلندا', 'slug' => 'نيوزيلندا'),
            array('country_code' => 'NI', 'name_en' => 'Nicaragua', 'name_ar' => 'نيكاراغوا', 'slug' => 'نيكاراغوا'),
            array('country_code' => 'NE', 'name_en' => 'Niger', 'name_ar' => 'النيجر', 'slug' => 'النيجر'),
            array('country_code' => 'NG', 'name_en' => 'Nigeria', 'name_ar' => 'نيجيريا', 'slug' => 'نيجيريا'),
            array('country_code' => 'NU', 'name_en' => 'Niue', 'name_ar' => 'نيوي', 'slug' => 'نيوي'),
            array('country_code' => 'NF', 'name_en' => 'Norfork Island', 'name_ar' => 'جزيرة نورفولك', 'slug' => 'جزيرة-نورفولك'),
            array('country_code' => 'MP', 'name_en' => 'Northern Mariana Islands', 'name_ar' => 'جزر ماريانا الشمالية', 'slug' => 'جزر-ماريانا-الشمالية'),
            array('country_code' => 'NO', 'name_en' => 'Norway', 'name_ar' => 'النرويج', 'slug' => 'النرويج'),
            array('country_code' => 'OM', 'name_en' => 'Oman', 'name_ar' => 'عُمان', 'slug' => 'عمان'),
            array('country_code' => 'PK', 'name_en' => 'Pakistan', 'name_ar' => 'باكستان', 'slug' => 'باكستان'),
            array('country_code' => 'PW', 'name_en' => 'Palau', 'name_ar' => 'بالاو', 'slug' => 'بالاو'),
            array('country_code' => 'PA', 'name_en' => 'Panama', 'name_ar' => 'بنما', 'slug' => 'بنما'),
            array('country_code' => 'PG', 'name_en' => 'Papua New Guinea', 'name_ar' => 'بابوا غينيا الجديدة', 'slug' => 'بابوا غينيا الجديدة'),
            array('country_code' => 'PY', 'name_en' => 'Paraguay', 'name_ar' => 'باراغواي', 'slug' => 'باراغواي'),
            array('country_code' => 'PE', 'name_en' => 'Peru', 'name_ar' => 'بيرو', 'slug' => 'بيرو'),
            array('country_code' => 'PH', 'name_en' => 'Philippines', 'name_ar' => 'الفلبين', 'slug' => 'الفلبين'),
            array('country_code' => 'PN', 'name_en' => 'Pitcairn', 'name_ar' => 'جزر بيتكيرن', 'slug' => 'جزر بيتكيرن'),
            array('country_code' => 'PL', 'name_en' => 'Poland', 'name_ar' => 'بولندا', 'slug' => 'بولندا'),
            array('country_code' => 'PT', 'name_en' => 'Portugal', 'name_ar' => 'البرتغال', 'slug' => 'البرتغال'),
            array('country_code' => 'PR', 'name_en' => 'Puerto Rico', 'name_ar' => 'بورتوريكو', 'slug' => 'بورتوريكو'),
            array('country_code' => 'QA', 'name_en' => 'Qatar', 'name_ar' => 'قطر', 'slug' => 'قطر'),
            array('country_code' => 'SS', 'name_en' => 'Republic of South Sudan', 'name_ar' => 'جنوب السودان', 'slug' => 'جنوب-السودان'),
            array('country_code' => 'RE', 'name_en' => 'Reunion', 'name_ar' => 'روينيون', 'slug' => 'روينيون'),
            array('country_code' => 'RO', 'name_en' => 'Romania', 'name_ar' => 'رومانيا', 'slug' => 'رومانيا'),
            array('country_code' => 'RU', 'name_en' => 'Russian Federation', 'name_ar' => 'روسيا', 'slug' => 'روسيا'),
            array('country_code' => 'RW', 'name_en' => 'Rwanda', 'name_ar' => 'رواندا', 'slug' => 'رواندا'),
            array('country_code' => 'KN', 'name_en' => 'Saint Kitts and Nevis', 'name_ar' => 'سانت كيتس ونيفيس', 'slug' => 'سانت-كيتس-ونيفيس'),
            array('country_code' => 'LC', 'name_en' => 'Saint Lucia', 'name_ar' => 'سانت لوسيا', 'slug' => 'سانت-لوسيا'),
            array('country_code' => 'VC', 'name_en' => 'Saint Vincent and the Grenadines', 'name_ar' => 'سانت فنسنت وجزر غرينادين', 'slug' => 'سانت-فنسنت-وجزر-غرينادين'),
            array('country_code' => 'WS', 'name_en' => 'Samoa', 'name_ar' => 'ساموا', 'slug' => 'ساموا'),
            array('country_code' => 'SM', 'name_en' => 'San Marino', 'name_ar' => 'سان مارينو', 'slug' => 'سان=مارينو'),
            array('country_code' => 'ST', 'name_en' => 'Sao Tome and Principe', 'name_ar' => 'ساو تومي وبرينسيبي', 'slug' => 'ساو-تومي-وبرينسيبي'),
            array('country_code' => 'SA', 'name_en' => 'Saudi Arabia', 'name_ar' => 'المملكة العربية السعودية', 'slug' => 'المملكة-العربية-السعودية'),
            array('country_code' => 'SN', 'name_en' => 'Senegal', 'name_ar' => 'السنغال', 'slug' => 'السنغال'),
            array('country_code' => 'RS', 'name_en' => 'Serbia', 'name_ar' => 'صربيا', 'slug' => 'صربيا'),
            array('country_code' => 'SC', 'name_en' => 'Seychelles', 'name_ar' => 'سيشل', 'slug' => 'سيشل'),
            array('country_code' => 'SL', 'name_en' => 'Sierra Leone', 'name_ar' => 'سيراليون', 'slug' => 'سيراليون'),
            array('country_code' => 'SG', 'name_en' => 'Singapore', 'name_ar' => 'سنغافورة', 'slug' => 'سنغافورة'),
            array('country_code' => 'SK', 'name_en' => 'Slovakia', 'name_ar' => 'سلوفاكيا', 'slug' => 'سلوفاكيا'),
            array('country_code' => 'SI', 'name_en' => 'Slovenia', 'name_ar' => 'سلوفينيا', 'slug' => 'سلوفينيا'),
            array('country_code' => 'SB', 'name_en' => 'Solomon Islands', 'name_ar' => 'جزر سليمان', 'slug' => 'جزر-سليمان'),
            array('country_code' => 'SO', 'name_en' => 'Somalia', 'name_ar' => 'الصومال', 'slug' => 'الصومال'),
            array('country_code' => 'ZA', 'name_en' => 'South Africa', 'name_ar' => 'جنوب أفريقيا', 'slug' => 'جنوب-أفريقيا'),
            array('country_code' => 'GS', 'name_en' => 'South Georgia South Sandwich Islands', 'name_ar' => 'جورجيا الجنوبية وجزر ساندويتش الجنوبية', 'slug' => 'جورجيا-الجنوبية-وجزر-ساندويتش-الجنوبية'),
            array('country_code' => 'ES', 'name_en' => 'Spain', 'name_ar' => 'إسبانيا', 'slug' => 'إسبانيا'),
            array('country_code' => 'LK', 'name_en' => 'Sri Lanka', 'name_ar' => 'سريلانكا', 'slug' => 'سريلانكا'),
            array('country_code' => 'SH', 'name_en' => 'St. Helena', 'name_ar' => 'سانت هيلانة', 'slug' => 'سانت-هيلانة'),
            array('country_code' => 'PM', 'name_en' => 'St. Pierre and Miquelon', 'name_ar' => 'سانت بيير وميكولون', 'slug' => 'سانت-بيير-وميكولون'),
            array('country_code' => 'SD', 'name_en' => 'Sudan', 'name_ar' => 'السودان', 'slug' => 'السودان'),
            array('country_code' => 'SR', 'name_en' => 'Suriname', 'name_ar' => 'سورينام', 'slug' => 'سورينام'),
            array('country_code' => 'SJ', 'name_en' => 'Svalbarn and Jan Mayen Islands', 'name_ar' => 'سفالبارد وجان مايان', 'slug' => 'سفالبارد-وجان-مايان'),
            array('country_code' => 'SZ', 'name_en' => 'Swaziland', 'name_ar' => 'سوازيلاند', 'slug' => 'سوازيلاند'),
            array('country_code' => 'SE', 'name_en' => 'Sweden', 'name_ar' => 'السويد', 'slug' => 'السويد'),
            array('country_code' => 'CH', 'name_en' => 'Switzerland', 'name_ar' => 'سويسرا', 'slug' => 'سويسرا'),
            array('country_code' => 'SY', 'name_en' => 'Syrian Arab Republic', 'name_ar' => 'سوريا', 'slug' => 'سوريا'),
            array('country_code' => 'TW', 'name_en' => 'Taiwan', 'name_ar' => 'تايوان', 'slug' => 'تايوان'),
            array('country_code' => 'TJ', 'name_en' => 'Tajikistan', 'name_ar' => 'طاجيكستان', 'slug' => 'طاجيكستان'),
            array('country_code' => 'TZ', 'name_en' => 'Tanzania, United Republic of', 'name_ar' => 'تنزانيا', 'slug' => 'تنزانيا'),
            array('country_code' => 'TH', 'name_en' => 'Thailand', 'name_ar' => 'تايلاند', 'slug' => 'تايلاند'),
            array('country_code' => 'TG', 'name_en' => 'Togo', 'name_ar' => 'توغو', 'slug' => 'توغو'),
            array('country_code' => 'TK', 'name_en' => 'Tokelau', 'name_ar' => 'توكيلو', 'slug' => 'توكيلو'),
            array('country_code' => 'TO', 'name_en' => 'Tonga', 'name_ar' => 'تونغا', 'slug' => 'تونغا'),
            array('country_code' => 'TT', 'name_en' => 'Trinidad and Tobago', 'name_ar' => 'ترينيداد وتوباغو', 'slug' => 'ترينيداد-وتوباغو'),
            array('country_code' => 'TN', 'name_en' => 'Tunisia', 'name_ar' => 'تونس', 'slug' => 'تونس'),
            array('country_code' => 'TR', 'name_en' => 'Turkey', 'name_ar' => 'تركيا', 'slug' => 'تركيا'),
            array('country_code' => 'TM', 'name_en' => 'Turkmenistan', 'name_ar' => 'تركمانستان', 'slug' => 'تركمانستان'),
            array('country_code' => 'TC', 'name_en' => 'Turks and Caicos Islands', 'name_ar' => 'جزر توركس وكايكوس', 'slug' => 'جزر-توركس-وكايكوس'),
            array('country_code' => 'TV', 'name_en' => 'Tuvalu', 'name_ar' => 'توفالو', 'slug' => 'توفالو'),
            array('country_code' => 'UG', 'name_en' => 'Uganda', 'name_ar' => 'أوغندا', 'slug' => 'أوغندا'),
            array('country_code' => 'UA', 'name_en' => 'Ukraine', 'name_ar' => 'أوكرانيا', 'slug' => 'أوكرانيا'),
            array('country_code' => 'AE', 'name_en' => 'United Arab Emirates', 'name_ar' => 'الإمارات العربية المتحدة', 'slug' => 'الإمارات-العربية-المتحدة'),
            array('country_code' => 'GB', 'name_en' => 'United Kingdom', 'name_ar' => 'المملكة المتحدة', 'slug' => 'المملكة-المتحدة'),
            array('country_code' => 'UM', 'name_en' => 'United States minor outlying islands', 'name_ar' => 'جزر الولايات المتحدة النائية', 'slug' => 'جزر-الولايات-المتحدة-النائية'),
            array('country_code' => 'UY', 'name_en' => 'Uruguay', 'name_ar' => 'أورغواي', 'slug' => 'أورغواي'),
            array('country_code' => 'UZ', 'name_en' => 'Uzbekistan', 'name_ar' => 'أوزبكستان', 'slug' => 'أوزبكستان'),
            array('country_code' => 'VU', 'name_en' => 'Vanuatu', 'name_ar' => 'فانواتو', 'slug' => 'فانواتو'),
            array('country_code' => 'VA', 'name_en' => 'Vatican City State', 'name_ar' => 'الفاتيكان', 'slug' => 'الفاتيكان'),
            array('country_code' => 'VE', 'name_en' => 'Venezuela', 'name_ar' => 'فنزويلا', 'slug' => 'فنزويلا'),
            array('country_code' => 'VN', 'name_en' => 'Vietnam', 'name_ar' => 'فيتنام', 'slug' => 'فيتنام'),
            array('country_code' => 'VG', 'name_en' => 'Virgin Islands (British)', 'name_ar' => 'جزر فيرجن البريطانية', 'slug' => 'جزر-فيرجن-البريطانية'),
            array('country_code' => 'VI', 'name_en' => 'Virgin Islands (U.S.)', 'name_ar' => 'جزر فيرجن التابعة للولايات المتحدة', 'slug' => 'جزر-فيرجن-التابعة-للولايات-المتحدة'),
            array('country_code' => 'WF', 'name_en' => 'Wallis and Futuna Islands', 'name_ar' => 'جزر والس وفوتونا', 'slug' => 'جزر-والس-وفوتونا'),
            array('country_code' => 'EH', 'name_en' => 'Western Sahara', 'name_ar' => 'الصحراء الغربية', 'slug' => 'الصحراء-الغربية'),
            array('country_code' => 'YE', 'name_en' => 'Yemen', 'name_ar' => 'اليمن', 'slug' => 'اليمن'),
            array('country_code' => 'YU', 'name_en' => 'Yugoslavia', 'name_ar' => 'يوغوسلافيا', 'slug' => 'يوغوسلافيا'),
            array('country_code' => 'ZR', 'name_en' => 'Zaire', 'name_ar' => 'زائير', 'slug' => 'زائير'),
            array('country_code' => 'ZM', 'name_en' => 'Zambia', 'name_ar' => 'زامبيا', 'slug' => 'زامبيا'),
            array('country_code' => 'ZW', 'name_en' => 'Zimbabwe', 'name_ar' => 'زيمبابوي', 'slug' => 'زيمبابوي'),
          ));

    }
}
